### PR TITLE
Pass state to `setContainerProps` call

### PR DESCRIPTION
**Pull request by i-am-the-slime**
I was just trying this and got this as a compile error. Passing state fixes it so I suppose that's correct.

### CODE REVIEW

**Comment by thomashoneyman** [comment]
Hey @i-am-the-slime -- thanks for taking the time to post an issue. I worked on the setters file recently and I don't believe the old version (for Halogen 4) or the new version (for Halogen 5) require passing state to any of the setters. For reference:

Halogen 5 (master)
https://github.com/citizennet/purescript-halogen-select/blob/21d63d1239c8859e15440103a4442a52b52242ff/src/Select/Setters.purs#L122

Halogen 4
https://github.com/citizennet/purescript-halogen-select/blob/c646a5502a7f5e7790e6d1977feb34216c08f9d3/src/Select/Setters.purs#L132

I'm not sure what would cause this error, but perhaps you simply need to delete your `output` folder and rebuild in case there are some stale modules in there? If that doesn't work, do you mind letting me know?

**Comment by thomashoneyman** [comment]
Closing this as `setContainerProps` should not require state.

**Comment by i-am-the-slime** [comment]
Thanks for having a look at this @thomashoneyman. Maybe there was indeed a caching problem, however this is a new project that never depended on an old version of Halogen or Halogen Select. I will have time to try this again over the weekend.

**Comment by i-am-the-slime** [comment]
I am sorry, I made a mistake. The actual place that `st` was needed.
I see you have changed this though:
https://github.com/citizennet/purescript-halogen-select/commit/21d63d1239c8859e15440103a4442a52b52242ff
Looks like everything's fine!

**Comment by thomashoneyman** [comment]
Yes, that was a bad slip on my part. Glad to hear things are working and thanks for reporting this!

**Pull request closed without merging**
